### ISSUE TITLE
Update ManageToken component

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#1003]
# ℹ️ Overview 

@stephclarkga I think that when a user clicks on an editable field there should be some type of visual icon (perhaps a checkmark next to the x) that the user can click to submit the changes. Right now it works if you hit enter. What do you think? 

Manage token form editing is still buggy please see [video](https://www.loom.com/share/b854c426555d47deb2220c4d34a4e29c) for unexpected behavior. 

@treasurechic When editing an input field, input validation happens when submitting a change, but not when the user clicks the x button. When a user clicks the x button the input field should revert to whatever was there before it. Also [per the documentation](https://developer.algorand.org/docs/get-details/asa/#modifying-an-asset) can you change the behavior so that the editable fields are only editable when the Manager Account matches the Connected Wallet? See screen shot below 

<img width="1434" alt="Screen Shot 2023-03-08 at 4 10 40 PM" src="https://user-images.githubusercontent.com/26069470/223850977-9e7305a5-59a3-4e01-986d-d1ba8c612223.png">

**Comment by treasurechic** [comment]
@ericsharma , there is a button below that user can click to update the changes. The "Update token" button

**Comment by ericsharma** [comment]
@treasurechic The update Token button is the button that is used to submit the manageToken change to the algorand blockchain. What I am talking about is an icon next to the individual form fields so a user doesn't have to hit enter to persist the changes to the UI.  I have attached a screenshot below to better help you understand what I mean.
<img width="794" alt="Screen Shot 2023-03-08 at 4 14 34 PM" src="https://user-images.githubusercontent.com/26069470/223851693-2839ffe2-19b6-4c43-9f13-c60b3ae547b3.png">

Also only the form field that is currently in focus should be editable so the screen shot above the x icon should only appear for the Reserve Address since it is in focus

**Comment by stephclarkga** [comment]
Agree that we could add an icon to submit a change but the user still has to click the button at the bottom of the page to submit the change to the blockchain, right? It needs to be clear that the user has not completed the change just by hitting that check if this is the case. I also assume multiple changes (eg I can edit the clawback and the freeze accounts) can be pushed in one transaction?

Also can we make these text entry fields longer? It would be great if the whole address can be seen in the text entry when active since it looks like we have the space?

**Comment by ericsharma** [comment]
@stephclarkga Correct, adding an icon will just submit the change to the UI for that specific field. The user will still need to click the button at the bottom of the page and sign the transaction to submit to the blockchain. Also correct again, multiple changes to the editable fields can be pushed to the blockchain in one transaction.
