### ISSUE TITLE
Add service fee to asset creation page

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#1041]
# ℹ️ Overview 
Following the [figma](https://www.figma.com/file/h8ghYImSd6atpjl5qavhW1/Algodex-Token-Launchpad?node-id=0-1&t=uIQvvXkihSHQwSRJ-0) add a service fee transaction to the create asset page

**Comment by ericsharma** [comment]
@stephclarkga can you check the latest deployment [on this branch](https://github.com/algodex/algodex-react/tree/1041-add-service-fee-to-asset-creation-page) for feedback on the service fee component?
I imagine that the tooltip message will change due to the increasing of the fee but let me know if there are any other changes that need to be made!

**Comment by stephclarkga** [comment]
Looks good! I will update the tooltip message. Did we decide if we want the ALGX balance to affect the fee?

**Comment by ericsharma** [comment]
@stephclarkga If the user has an adequate ALGX balance then they forego the fee entirely. I was planning on conditionally showing the service fee note only when the wallet does not have adequate ALGX balance. Do you think there should be some kind of disclaimer? 

Another way to do it would be to always shows the service fee note and conditionally change the `1000algo` service fee when ALGX balance is detected. I'll defer to whatever you think is best!

**Comment by stephclarkga** [comment]
I think we should have some callout even if the fee has been removed with the ALGX balance to show value of the ALGX tokens so I would probably do the second option
