### ISSUE TITLE
🐛 Fix: page previews / thumbnails for landing page aren't working on Twitter (maybe Google as well). Needed for SEO

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-react#561]
# ℹ Overview

https://app.algodex.com/about is not creating any thumbnails on Twitter

 - Add more Twitter Card metadata
 - Reduce front page image size with `next/image` or optimize it for web in photo editor

https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started

```jsx
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="@AlgodexOfficial" />
<meta name="twitter:title" content="Algodex" />
<meta name="twitter:description" content="Wow!" />
<meta name="twitter:image" content="https://example.com/amazing_image.jpeg" />
```

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

**Comment by hasyminh** [comment]
Please check if our logo can be shown in the thumbnail? 
![image](https://user-images.githubusercontent.com/39449399/198310839-725d7b14-b5a7-42b7-bf50-eb9493318104.png)
