### ISSUE TITLE
🐛 Fix: Balance is not updated after Purchasing coin

### ISSUE THREAD

**Issue by alchemist-bounty** [algodex/algodex-react#641]
# ℹ Overview

https://testnet.algodex.com/trade/51099062?cc=US
After we purchase 2USDC from 1 Algo, USDC balance is not updated although it shows the transaction correctly.
If we try same steps on this coin https://testnet.algodex.com/trade/37074699?cc=US it works fine.
![image](https://user-images.githubusercontent.com/76131191/181381940-4f97586b-6e78-404b-871c-cbd18998c2d3.png)

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

**Comment by atrefonas** [comment]
Just confirmed this isn't an issue now.
