### ISSUE TITLE
Feature: The trade history should automatically scroll to the top whenever new data comes in

### ISSUE THREAD

**Issue by IYTEC** [algodex/algodex-react#734]
# ℹ Overview
Trade order should automatically scroll to the top of the table when new order comes in

**Comment by atrefonas** [comment]
I think this is fixed now? @IYTEC

**Comment by IYTEC** [comment]
Yes, this is fixed

**Comment by atrefonas** [comment]
"Yes, this is fixed" please in future close issues when commenting it is fixed.
