### ISSUE TITLE
Fix: Use the right market order price for Buy and Sell Orders

### ISSUE THREAD

**Issue by IYTEC** [algodex/algodex-react#736]
# ℹ Overview
https://www.loom.com/share/4549d750dd8f4e53b30fd217a0bea62e?t=88
<img width="690" alt="Screen Shot 2022-08-30 at 9 10 08 AM" src="https://user-images.githubusercontent.com/13381770/187467980-cf885626-50d2-43b3-808c-8b66460b1edc.png">

**Comment by atrefonas** [comment]
I think this is fixed

**Comment by IYTEC** [comment]
Yes, this is fixed

**Comment by atrefonas** [comment]
@IYTEC next time pls when you comment something is fixed please also close the issue 😃 .
