### ISSUE TITLE
Fix: Support Link, Increase Button Size, Add Algo Icon

### ISSUE THREAD

**Issue by IYTEC** [algodex/algodex-react#737]
# ℹ Overview
Support Link in footer, should be [current vercel domain]/support
Increase Connect Button Size on Mobile
Add Algo Icon to Orderbook Total

**Comment by atrefonas** [comment]
I think these were fixed? Please confirm @IYTEC

**Comment by IYTEC** [comment]
Yes, this is fixed @atrefonas

**Comment by atrefonas** [comment]
Hi @IYTEC when an issue is fixed, kindly close the issue on Github, instead of just commenting it is fixed.
