### ISSUE TITLE
Fix: Algo amount needs to be white to match what is on Testnet

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-react#747]
# ℹ Overview

This is the way it should look. The big numbers for algo amount need to be white here, surrounding text stays gray.

![image](https://user-images.githubusercontent.com/72869083/193111399-f6e5004a-1eaf-4082-b0b2-189835a12af2.png)

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

**Comment by IYTEC** [comment]
This issue is fixed in https://github.com/algodex/algodex-react/issues/781
