### ISSUE TITLE
Acceptance: useReducer Wallet Management

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#750]
# ℹ Overview

Branch to build out useReducer Wallet Management

### 📝 Related Issues
- [x] #751
- [x] #753
- [x] #755
- [x] #756

**Comment by atrefonas** [comment]
This needs to be redone as a branch of the current development branch. There should be a big refactoring of the current wallet management to switch it to a useReducer, using some of the things @ericsharma came up with, but with more refinement.
