### ISSUE TITLE
Fix: Show more decimals for the price in Open Orders and Order History 

### ISSUE THREAD

**Issue by hasyminh** [algodex/algodex-react#772]
The price is showing 4 decimals instead of 6.
![image](https://user-images.githubusercontent.com/39449399/195103845-23100f03-fc33-4b78-89f8-98d41c15c6a1.png)

**Comment by atrefonas** [comment]
Check the decimal fixes that @alchemist-bounty made in some past PRs @IYTEC

**Comment by IYTEC** [comment]
Got it @atrefonas

**Comment by IYTEC** [comment]
I think its related to this
https://github.com/algodex/algodex-react/pull/595

**Comment by IYTEC** [comment]
@atrefonas @ericsharma. To fix this issue, we need to update the `floatToFixed` implementation on the SDK to the new logic
 ```
 export const floatToFixed = (float, minDigits = 4, maxDigits = 6) => {
  if (typeof float === 'undefined') throw new Error('Must have a valid float')
  let numDigits

  const absValue = new Big(float).abs().toNumber()
  // checks for fractional numbers less than zero with preceding zeros after decimal point
  if (absValue > 0 && absValue < 0.1) {
    // if number is 0.0001, fractionalStr is '0001'
    const fractionalStr = new Big(float).toFixed(maxDigits).toString().split('.')[1]
    let precedingZeros = fractionalStr.length
    if (precedingZeros >= minDigits && precedingZeros <= maxDigits) {
      numDigits = precedingZeros
    } else {
      numDigits = minDigits
    }
  } else {
    // number of digits decide number of decimals
    const decimalStr = new Big(float).toFixed(maxDigits).toString().split('.')[0]
    if (decimalStr.length > 6) {
      numDigits = 0
    } else if (decimalStr.length > 2 && decimalStr.length < maxDigits) {
      numDigits = 7 - decimalStr.length
    } else if (decimalStr.length <= 2) {
      numDigits = 7 - 1
    } else if (decimalStr.length == maxDigits) {
      numDigits = 7 - maxDigits
    } else {
      numDigits = 0
    }
  }
  return new Big(float).toFixed(numDigits)
}
```

**Comment by IYTEC** [comment]
The implementation for floatToFixed exist on the SDK here:
```https://github.dev/algodex/algodex-sdk/blob/5394f2b3db8be2ca32f7ece605b81bab85937bd9/lib/utils/format/floatToFixed.js#L28```

**Comment by atrefonas** [comment]
If algodex-react calls it directly, can you just add the new one into a
file in algodex-react?

**Comment by IYTEC** [comment]
Yes, we can do that @atrefonas, but the SDK also needs it. It's used in different parts of the SDK.

**Comment by IYTEC** [comment]
Its used here:

```
https://github.dev/algodex/algodex-sdk/blob/5394f2b3db8be2ca32f7ece605b81bab85937bd9/lib/order/http/AlgodexClient.js#L174
```

**Comment by atrefonas** [comment]
@IYTEC can you make the PR in algodex-sdk?

**Comment by IYTEC** [comment]
Yes, can do that.

**Comment by IYTEC** [comment]
Will create an issue now.

**Comment by atrefonas** [comment]
As discussed in Slack please leave the SDK alone for this one and make a floatToFixedDisplay function instead in algodex-react, since it is used for display while the SDK one is used for computation
