### ISSUE TITLE
Fix: Freeze the bottom Menu bar when scrolling up the token information page

### ISSUE THREAD

**Issue by hasyminh** [algodex/algodex-react#803]
https://user-images.githubusercontent.com/39449399/196004708-340a4ffc-4ba5-4d7c-8e3a-21973ace9de3.mp4

**Comment by hasyminh** [comment]
Look like this happens on Android only. I checked with IOS, no such issue.

**Comment by IYTEC** [comment]
Hi @hasyminh, please, I can't replicate this issue both on my Android and iOS.
