### ISSUE TITLE
Fix: Can't open orders due to insufficient avaialable balance

### ISSUE THREAD

**Issue by hasyminh** [algodex/algodex-react#846]
https://user-images.githubusercontent.com/39449399/198445584-c8300e0b-27ae-4bed-b8ad-423f926bb91f.mp4

I tried to open an order with 100% of my balance but not going through, although the messages said "successfully".
When I reduced the amount, it went through.
The ALGO balance shown on the UI is the original balance of the wallet. We should show the AVAILABLE balance after subtracting the ALGO amount to be kept in the wallet

**Comment by atrefonas** [comment]
This is fixed now I think
