### ISSUE TITLE
Add styling for unconnected wallet state

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#951]
# ℹ️ Overview
We need to have a styled representation of the scenario where a user navigates to the page when a wallet is not connected

## When wallet is connected

<img width="1251" alt="ConnectedState" src="https://user-images.githubusercontent.com/26069470/218209250-c308fee6-736f-4fed-be01-db6685295b87.png">

## When wallet is not connected
<img width="1242" alt="UnconnectedState" src="https://user-images.githubusercontent.com/26069470/218209293-8e123911-3dfd-4d72-8bce-c0fd89a32bc5.png">

### ToDo :
@stephclarkga Adds designs to the Figma for when wallet is not connected (Right now all the designs have the wallet already connected)
@treasurechic adds the styles from Figma to the below branch

**Comment by stephclarkga** [comment]
Updated the Figma file with disconnected wallet states for each page - https://www.figma.com/file/h8ghYImSd6atpjl5qavhW1/Algodex-Token-Launchpad?node-id=0%3A1&t=qu1dkQGCcEGR2Ob9-1

**Comment by treasurechic** [comment]
@ericsharma , this update has been added and pushed to this branch, which branch do you want the PR to go into?

**Comment by ericsharma** [comment]
@treasurechic I do not see the changes in the commits of this branch, are you sure your pushed them [to branch 951](https://github.com/algodex/algodex-react/tree/951-add-styling-for-unconnected-wallet-state)?

**Comment by treasurechic** [comment]
@ericsharma , I just noticed I did not push it🤦🏾‍♀️. I just did, you should see it now
