### ISSUE TITLE
Add validation to CreateToken form inputs

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#955]
# ℹ️ Overview
In `CreateToken.tsx`  in the onSubmit function, ensure the `formData` inputs are valid. Throw an error message and prevent submission if they are not valid. 

Requirements: 
   - tokenName - string with no spaces
   - unitName - string with no spaces
   - totalSupply - whole number 
   - decimals - whole number between 1-10
   - assetURL - valid url string
   - clawbackAddr - valid algorand wallet string || null
   - reserveAddr - valid algorand wallet string || null
   - managerAddr - valid algorand wallet string || null
   - freezeAddr - valid algorand wallet string || null

**Comment by treasurechic** [comment]
@ericsharma , this task is completed, and branch updated✅

**Comment by ericsharma** [comment]
@treasurechic Great! Can you open a pull request into branch #942 and mark me for review?
