### ISSUE TITLE
Add disconnect wallet button to CreateToken component

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-react#970]
# ℹ️ Overview 
Right now there is no way to disconnect a wallet on any of the Launchpad components. @stephclarkga I think that giving the user a way to disconnect their wallet without having to navigate to the trade page is something that should be present on all Launchpad components. What do you think?

## 🛠 Requirements
- [x] Figma update to have a disconnect wallet option
- [x] #988

**Comment by stephclarkga** [comment]
Added dropdown menus from the Wallet button in the header. If no wallet is connected, then this dropdown shows with the option to connect with the different wallet types we offer. <img width="882" alt="Screen Shot 2023-02-27 at 4 27 58 PM" src="https://user-images.githubusercontent.com/59464107/221689700-b6f40b81-5646-4c15-94c7-d4673b9b063f.png">
When a wallet is connected, a Disconnect button is in the dropdown and I also added a message explaining only one wallet can be connected at a time. <img width="915" alt="Screen Shot 2023-02-27 at 4 28 11 PM" src="https://user-images.githubusercontent.com/59464107/221689711-c2efbf60-065a-4459-b3e0-bfda53029059.png">

These are at the top in the Figma file here: https://www.figma.com/file/h8ghYImSd6atpjl5qavhW1/Algodex-Token-Launchpad?node-id=0%3A1&t=BsRd74haiuQexKjx-1

**Comment by ericsharma** [comment]
@stephclarkga I see the appeal of keeping the disconnect button in the header but from an implementation standpoint it is not great since this behavior is different to how the `Connect a Wallet` dropdown behaves on the trade page. Headers and their corresponding components should be for logic that is commonly shared throughout our application and conditionally changing the way a certain header component behaves depending on what page we are on goes against that design principle.

**Comment by stephclarkga** [comment]
@ericsharma I agree that ideally the header acts the same throughout. I thought launchpad already had different behavior and was working with that, my bad! 

We can do something like this temporarily and have the button next to the wallet address on the page: <img width="908" alt="Screen Shot 2023-02-28 at 10 31 12 AM" src="https://user-images.githubusercontent.com/59464107/221900572-7449f68c-49e8-4097-a9cc-cf53f05f674c.png">

**Comment by ericsharma** [comment]
@stephclarkga Sweet I think this is a happy middle ground for the time being! This will be easy to swap out once we move the entire wallet management into a header modal for both trade and launchpad pages 🥳
